config/routes.rb
Rails.application.routes.draw do

  # Root
  root 'static#index'

  # Static
  get 'service'     => 'static#service'
  get 'custom'      => 'static#custom'
  get 'contacts'    => 'static#contacts'

  # Advertising
  get 'advertising/ford-focus-2-zamena-scepleniya'    => 'advertising#ford-focus-2-zamena-scepleniya'

  # User Activities
  match 'codeword_request', to: 'user_activities#codeword_request', via: 'post'
  match 'price_request',    to: 'user_activities#price_request',    via: 'post'
  match 'callback_request', to: 'user_activities#callback_request', via: 'post'
  match 'new_feedback',     to: 'user_activities#new_feedback',     via: 'post'

  # Gallery
  get 'gallery',                            to: 'collections#index',  as: 'collections'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :media_collections, dependent: :destroy
  has_many :media, through: :media_collections
end

app/models/media_collection.rb
class MediaCollection < ActiveRecord::Base
  belongs_to :collection
  belongs_to :medium
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  has_many :media_collections, dependent: :destroy
  has_many :collections, through: :media_collections
end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
end

app/controllers/advertising_controller.rb
class AdvertisingController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_route

  private

  def set_route
    @route = Route.find_by name: "#{params[:controller]}##{params[:action]}##{params[:id]}"
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show]

  # GET /collection/1
  def show
    @media = @collection.media.order :created_at
  end

  def index
    @covers = {}
    @collections = Collection.where(published: true).order :position
    @collections.each do |collection|
      @covers[collection.id] =
        collection.media.references(:media_collections).where(media_collections: {cover: true})
    end
    @media = Medium.all
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController

  def codeword_request
    @user_activity = UserActivity.new(codeword_request_params)
    if @user_activity.save
      redirect_to :back, notice: {title: 'Поздравляем!', text: "Ваш промо-код: 3104"}
    else
      redirect_to :back, notice: {title: 'Ошибка', text: 'Попробуйте повторить позже.'}
    end
  end

  def price_request
    @user_activity = UserActivity.new(price_request_params)
    if @user_activity.save
      redirect_to :back, notice: {title: 'Спасибо!', text: 'Мы сообщим Вам стоимость запчастей в ближайшее время.'}
    else
      redirect_to :back, notice: {title: 'Ошибка', text: 'Попробуйте повторить позже.'}
    end
  end

  def callback_request
    @user_activity = UserActivity.new(callback_request_params)
    if @user_activity.save
      redirect_to :back, notice: {title: 'Спасибо!', text: 'Мы свяжемся с Вами в ближайшее время.'}
    else
      redirect_to :back, notice: {title: 'Ошибка!', text: 'Попробуйте повторить позже.'}
    end
  end

  def new_feedback
    @user_activity = UserActivity.new(feedback_params)
    if @user_activity.save
      redirect_to contacts_path, notice: {title: 'Спасибо!', text: 'Мы ответим Вам в ближайшее время.'}
    else
      redirect_to contacts_path, notice: {title: 'Ошибка!', text: 'Попробуйте повторить позже.'}
    end
  end

  private

  def user_activity_params
    params.permit(:session_id, :source, :action, :user_info)
  end

  def codeword_request_params
    params[:user_info] = ''
    user_activity_params
  end

  def price_request_params
    params[:user_info] = JSON.generate(params.permit(:name, :phone, :vin))
    user_activity_params
  end

  def callback_request_params
    params[:user_info] = JSON.generate(params.permit(:name, :phone))
    user_activity_params
  end

  def feedback_params
    params[:user_info] = JSON.generate(params.permit(:name, :email, :message))
    user_activity_params
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_activity_helper.rb
module UserActivityHelper

  def user_activity_source
    "#{params[:controller]}:#{params[:action]}"
  end

end

app/views/advertising/ford-focus-2-zamena-scepleniya.html.haml
%main.advertising

  %section.hero
    .data-container
      .inner
        %h1.title Ford Focus 2.<br>Замена сцепления по акции
        %p.text Назовите промо-код и получите скидку <b>1000р</b> на работу по замене сцепления Ford&nbsp;Focus&nbsp;2 в автосервисе TechRacing.
        = form_tag codeword_request_path, method: 'post' do
          = hidden_field_tag :session_id , session.id
          = hidden_field_tag :source , user_activity_source
          = submit_tag 'Получить промо-код', class: 'cta'

  %section.price
    .data-container
      %h2.section-title Стоимость работ по замене сцепления Ford Focus 2.
      .desc
        .text &nbsp;
        .text Стоимость работ с учетом скидки по акции составит:
        .text В процессе ремонта стоимость работ не увеличивается:
        .text Вы не услышите другие цифры, когда позвоните нам:
        .text Вы получаете диагностику подвески:
      .card
        .title Бензиновый двигатель
        .text <strike>5999р</strike> 4999р
        .text
          %i.material-icons &#xE876;
        .text
          %i.material-icons &#xE876;
        .text в подарок
      .card
        .title Дизельный двигатель
        .text <strike>6499р</strike> 5499р
        .text
          %i.material-icons &#xE876;
        .text
          %i.material-icons &#xE876;
        .text в подарок

  %section.spare-parts
    .data-container
      %h2.section-title Лучшая цена на запчасти
      %p.text Заполните форму, чтобы получить самое выгодное предложение на комплект сцепления именно для Вашего автомобиля. VIN-номер необходим для точного подбора запчастей.

      .spare-parts-form
        = form_tag price_request_path, method: "post", id: 'js-price-request-validate' do

          = hidden_field_tag :session_id , session.id
          = hidden_field_tag :source , user_activity_source

          .form-input
            = text_field_tag :name, '', class: 'form-control', required: '', placeholder: 'Имя *'

          .form-input
            = text_field_tag :phone, '', class: 'form-control', required: '', placeholder: 'Телефон *', :"data-mask" => '(999) 999-9999'

          .form-input
            = text_field_tag :vin, '', class: 'form-control', required: '', placeholder: 'VIN-номер *'

          = submit_tag 'Узнать стоимость запчастей', class: 'cta'

= render 'static/flash_modal'

app/views/collections/index.html.haml
%main.collections
  .header-theme

  %section.hero
    .data-container
      .inner
        .meta-data
          Альбомов:
          = @collections.size
          •
          Фотографий:
          = @media.size
        .contacts
          СПб, Кондратьевский пр-кт, д.2, корп.4Б • (812)677-48-47

app/views/layouts/_footer.html.haml
%footer
  .data-container
    .footer-middle
      %nav.service
        %span Автосервис
        %ul
          %li
            %a Диагностика автомобиля
          %li
            %a Техническое обслуживание
          %li
            %a Ремонт ходовой части
          %li
            %a Ремонт тормозных систем
          %li
            %a Ремонт двигателей
          %li
            %a Автоэлектрика
      %nav.custom
        %span Тюнинг
        %ul
          %li
            %a Доработка двигателей
          %li
            %a Свап проекты
          %li
            %a Каркасы безопасности
          %li
            %a Выпускные системы
          %li
            %a Настройка ECU
          %li
            %a Кастом
      %nav.contacts
        %span Контакты
        %ul
          %li 195009, Санкт-Петербург, Кондратьевский&nbsp;пр-кт,&nbsp;д.2,&nbsp;корп.4Б
        %ul
          %li
            %a{href: "tel:+79995274847"}+7 (999) 527-48-47
          %li
            %a{href: "tel:+78126774847"}+7 (812) 677-48-47
        %ul
          %li
            e-mail:&nbsp;
            %a{:href => "mailto:welcome@techracing.ru"}welcome@techracing.ru
    %hr
    .footer-lower
      .copyright
        %span © #{Time.now.year} TechRacing
      .location
        %span Санкт-Петербург

app/views/layouts/_header.html.haml
%header
  .data-container
    %nav.navbar
      .tr-logo
        = link_to image_tag('logo.png', alt: 'TechRacing логотип'), root_path

      .navbar-toggle
        %i.material-icons.md-light{id: 'js-navbar-toggle'} &#xE5D2;

      .navbar-nav{id: 'js-navbar-nav'}
        .navbar-link
          = link_to 'Сервис', service_path
        .navbar-link
          = link_to 'Тюнинг', custom_path
        .navbar-link
          = link_to 'Наши работы', collections_path
        .navbar-link
          = link_to 'Контакты', contacts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <% if @route %>
      <title><%= @route.title %></title>
      <meta name="description" content="<%= @route.description %>" />
      <meta name="keywords" content="<%= @route.keywords %>" />
    <% end %>

    <link rel="icon" href="http://techracing.ru/favicon.ico" type="image/x-icon">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <%= javascript_include_tag 'application', async: true, 'data-turbolinks-track' => true %>

    <% if Rails.env.production? %>
      <script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter30517107 = new Ya.Metrika({id:30517107, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/30517107" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <% end %>

    <script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>

  </body>

</html>